config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  post "home/send_mail"

  resources :contacts
  resources :clients
  resources :features
  resources :information

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def send_mail
  	UserResponseMailer.user_response(params).deliver
    # flash[:success] = 'Your message sent successfully to Atul. Thanks for your message. Keep in touch'
    p "******333******#{params.inspect}***********333**"
    redirect_to :back
  end

 private

 protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/clients/index.html.haml
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %title Span Engineering
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "http://bootstraptaste.com", :name => "author"}/
    / css
    %link{:href => "/assets/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "/assets/jquery.fancybox.css", :rel => "stylesheet"}
    %link{:href => "/assets/flexslider.css", :rel => "stylesheet"}/
    %link{:href => "/assets/style.css", :rel => "stylesheet"}/
    / Theme skin
    %link{:href => "/assets/default.css", :rel => "stylesheet"}/
    / HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  %body
    #wrapper
      / start header
      %header
        .navbar.navbar-default.navbar-static-top
          .container
            .navbar-header
              %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              %a.navbar-brand{:href => ""}
                %span> Span Engineering
            .navbar-collapse.collapse
              %ul.nav.navbar-nav
                %li
                  = link_to "Home", root_path
                %li
                  = link_to "About Us", information_index_path
                %li
                  = link_to "Clients", clients_path
                %li
                  = link_to "Features", features_path
                %li
                  = link_to "Contact Us",contacts_path
      %section#content
        .container
          .row.center
            .col-lg-3
              %h4.heading ISO Certificate
              .row
                %section#projects
                  %ul#thumbs.portfolio
                    / Item Project and Filter Name
                    %li.col-lg-10.design{"data-id" => "id-0", "data-type" => "web"}
                      .item-thumbs 
                        / Fancybox - Gallery Enabled - Title - Full Image
                        %a.hover-wrap.fancybox{"data-fancybox-group" => "gallery", :href => "/assets/certificate.jpg", :title => "Work 1"}
                          %span.overlay-img
                          %span.overlay-img-thumb.font-icon-plus
                        / Thumb Image and Description
                        %img{:alt => "Quality Work", :src => "assets/certificate.jpg"}/
                   
            .col-lg-9
              %h4.heading Some of our big Clients
              .row
                %section#projects
                  %ul#thumbs.portfolio
                    / Item Project and Filter Name
                    %li.col-lg-4.design{"data-id" => "id-0", "data-type" => "web"}
                      .item-thumbs
                        / Fancybox - Gallery Enabled - Title - Full Image
                        %a.hover-wrap.fancybox{"data-fancybox-group" => "gallery", :href => "/assets/client1.jpg", :title => "Work 1"}
                          %span.overlay-img
                          %span.overlay-img-thumb.font-icon-plus
                        / Thumb Image and Description
                        %img{:alt => "Quality Work", :src => "assets/client1.jpg"}/
                    / End Item Project
                    / Item Project and Filter Name
                    %li.item-thumbs.col-lg-4.design{"data-id" => "id-1", "data-type" => "icon"}
                      / Fancybox - Gallery Enabled - Title - Full Image
                      %a.hover-wrap.fancybox{"data-fancybox-group" => "gallery", :href => "/assets/client7.jpg", :title => "Work 2"}
                        %span.overlay-img
                        %span.overlay-img-thumb.font-icon-plus
                      / Thumb Image and Description
                      %img{:alt => "Quality Work", :src => "/assets/client7.jpg"}/
                    / End Item Project
                    / Item Project and Filter Name
                    %li.item-thumbs.col-lg-4.photography{"data-id" => "id-2", "data-type" => "illustrator"}
                      / Fancybox - Gallery Enabled - Title - Full Image
                      %a.hover-wrap.fancybox{"data-fancybox-group" => "gallery", :href => "/assets/client5.jpg", :title => "Work 3"}
                        %span.overlay-img
                        %span.overlay-img-thumb.font-icon-plus
                      / Thumb Image and Description
                      %img{:alt => "Quality Work", :src => "/assets/client5.jpg"}/
                    / End Item Project
                    / Item Project and Filter Name
                    %li.item-thumbs.col-lg-4.photography{"data-id" => "id-2", "data-type" => "illustrator"}
                      / Fancybox - Gallery Enabled - Title - Full Image
                      %a.hover-wrap.fancybox{"data-fancybox-group" => "gallery", :href => "/assets/client4.jpg", :title => "Work 4"}
                        %span.overlay-img
                        %span.overlay-img-thumb.font-icon-plus
                      / Thumb Image and Description
                      %img{:alt => "Quality Work", :src => "/assets/client4.jpg", :height => "720", :width => "1280"}/
                    %li.item-thumbs.col-lg-4.photography{"data-id" => "id-2", "data-type" => "illustrator"}
                      / Fancybox - Gallery Enabled - Title - Full Image
                      %a.hover-wrap.fancybox{"data-fancybox-group" => "gallery", :href => "/assets/client2.jpg", :title => "Work 4"}
                        %span.overlay-img
                        %span.overlay-img-thumb.font-icon-plus
                      / Thumb Image and Description
                      %img{:alt => "Quality Work", :src => "/assets/client2.jpg", :height => "720", :width => "1280"}/
                    %li.item-thumbs.col-lg-4.photography{"data-id" => "id-2", "data-type" => "illustrator"}
                      / Fancybox - Gallery Enabled - Title - Full Image
                      %a.hover-wrap.fancybox{"data-fancybox-group" => "gallery", :href => "/assets/client6.jpg", :title => "Work 4"}
                        %span.overlay-img
                        %span.overlay-img-thumb.font-icon-plus
                      / Thumb Image and Description
                      %img{:alt => "Quality Work", :src => "/assets/client6.jpg", :height => "720", :width => "1280"}/  
      %footer
        .container
          .row
            .col-lg-5
              .widget
                %h5.widgetheading Get in touch with us
                %address
                  %strong Span Engineering
                  %br/
                  Gat No. 324, Chakan MIDC Phase II
                  %br/
                  Bhamboli, Tal - Khed, Dist - Pune
                %p
                  %i.icon-phone
                  8806315314 / 9130140895
                  %br/
                  %i.icon-envelope-alt
                  spanengineering25@gmail.com
            .col-lg-3
              .widget
                %h5.widgetheading Pages
                %ul.link-list
                  %li
                    = link_to "Home", root_path
                  %li
                    = link_to "About Us", information_index_path
                  %li
                    = link_to "Clients", clients_path
                  %li
                    = link_to "Features", features_path
                  %li
                    = link_to "Contact Us",contacts_path
            .col-lg-4
              .widget
                %h5.widgetheading © Span Engineering 2016
                %p
                  %address
                  %p
                    %strong Social Medial Links
                    %ul.social-network
                      %li
                        %a{"data-placement" => "top", :href => "https://www.facebook.com/Span-Engineering-Pvt-Ltd-Chakan-521609734702691/", :title => "Facebook", :target => "_blank"}
                          %i.fa.fa-facebook
                      %li
                        %a{"data-placement" => "top", :href => "https://twitter.com/SpanEngineering", :title => "Twitter", :target => "_blank"}
                          %i.fa.fa-twitter
                      %li
                        %a{"data-placement" => "top", :href => "https://in.linkedin.com/in/vishal-shivekar-97411812b", :title => "Linkedin", :target => "_blank"}
                          %i.fa.fa-linkedin
                      %li
                        %a{"data-placement" => "top", :href => "https://plus.google.com/u/0/101736486493236478496", :title => "Google plus", :target => "_blank"}
                          %i.fa.fa-google-plus
                %span Site Developed By
                %a{:href => "https://www.facebook.com/atul.nikhade", :target => "_blank"} Atul Nikhade
                .clear
    %a.scrollup{:href => "#"}
      %i.fa.fa-angle-up.active
    /
      javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:src => "/assets/jquery.js"}
    %script{:src => "/assets/jquery.easing.1.3.js"}
    %script{:src => "/assets/bootstrap.min.js"}
    %script{:src => "/assets/jquery.fancybox.pack.js"}
    %script{:src => "/assets/jquery.fancybox-media.js"}
    %script{:src => "/assets/prettify.js"}
    %script{:src => "/assets/jquery.quicksand.js"}
    %script{:src => "/assets/setting.js"}
    %script{:src => "/assets/jquery.flexslider.js"}
    %script{:src => "/assets/animate.js"}
    %script{:src => "/assets/custom.js"}

app/views/clients/show.html.erb
<h1>Clients#show</h1>
<p>Find me in app/views/clients/show.html.erb</p>

app/views/contacts/index.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %title Moderna - Bootstrap 3 flat corporate template
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "http://bootstraptaste.com", :name => "author"}/
    / css
    %link{:href => "css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "css/fancybox/jquery.fancybox.css", :rel => "stylesheet"}/
    %link{:href => "css/jcarousel.css", :rel => "stylesheet"}/
    %link{:href => "css/flexslider.css", :rel => "stylesheet"}/
    %link{:href => "css/style.css", :rel => "stylesheet"}/
    / Theme skin
    %link{:href => "skins/default.css", :rel => "stylesheet"}/
    / HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  %body
    #wrapper
      / start header
      #wrapper
      / start header
      %header
        .navbar.navbar-default.navbar-static-top
          .container
            .navbar-header
              %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              %a.navbar-brand{:href => ""}
                %span> Span Engineering
            .navbar-collapse.collapse
              %ul.nav.navbar-nav
                %li
                  = link_to "Home", root_path
                %li
                  = link_to "About Us", information_index_path
                %li
                  = link_to "Clients", clients_path
                %li
                  = link_to "Features", features_path
                %li
                  = link_to "Contact Us",contacts_path  
      / end header
      %section#inner-headline
        .container
          .row
            .col-lg-12
              %ul.breadcrumb
                %li
                  %a{:href => "#"}
                    %i.fa.fa-home
                  %i.icon-angle-right
                %li.active Contact
      %section#content
        .map
          %div{:style => "width:1400px;overflow:hidden;height:500px;max-width:100%;"}
            #gmap-canvas{:style => "height:100%; width:100%;max-width:100%;"}
              %iframe{:frameborder => "0", :src => "https://www.google.com/maps/embed/v1/place?q=Bhamchandra+Madhyamic+Vydhyalaya,+Bhamboli,+Maharashtra,+India&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU", :style => "height:100%;width:100%;border:0;"}
            %a#authorize-maps-data.embedded-map-html{:href => "http://www.szablonypremium.pl", :rel => "nofollow"} http://www.szablonypremium.pl
            :css
              #gmap-canvas .text-marker{max-width:none!important;background:none!important;}img{max-width:none}
          %script{:async => "async", :defer => "defer", :src => "https://www.szablonypremium.pl/google-maps-authorization.js?id=7290c751-ea52-5211-29c5-e73a42697ebb&c=embedded-map-html&u=1475739973"}


        .container
          .row
            .col-lg-12
              %h4
                Get in touch with us by filling
                %strong contact form below
              %form#contactform.validateform{:action => "/home/send_mail", :method => "post", :name => "send-contact"}
                #sendmessage
                  Your message has been sent. Thank you!
                .row
                  .col-lg-4.field
                    %input{"data-msg" => "Please enter at least 4 chars", "data-rule" => "maxlen:4", :name => "name", :placeholder => "* Enter your full name", :type => "text"}/
                    .validation
                  .col-lg-4.field
                    %input{"data-msg" => "Please enter a valid email", "data-rule" => "email", :name => "email", :placeholder => "* Enter your email address", :type => "text"}/
                    .validation
                  .col-lg-4.field
                    %input{"data-msg" => "Please enter at least 4 chars", "data-rule" => "maxlen:4", :name => "subject", :placeholder => "Enter your subject", :type => "text"}/
                    .validation
                  .col-lg-12.margintop10.field
                    %textarea.input-block-level{"data-msg" => "Please write something", "data-rule" => "required", :name => "message", :placeholder => "* Your message here...", :rows => "12"}
                    .validation
                    %p
                      %button.btn.btn-theme.margintop10.pull-left{:type => "submit"} Submit message
                      %span.pull-right.margintop20 * Please fill all required form field, thanks!
      .container
        .row
          .col-lg-6
            .copyright
              %p
                %span © Span Engineering 2016 All right reserved.
                %br
                %span Developed By
                %a{:href => "https://www.facebook.com/atul.nikhade", :target => "_blank"} Atul Nikhade
          .col-lg-6
            %ul.social-network
              %li
                %a{"data-placement" => "top", :href => "https://www.facebook.com/Span-Engineering-Pvt-Ltd-Chakan-521609734702691/", :title => "Facebook", :target => "_blank"}
                  %i.fa.fa-facebook
              %li
                %a{"data-placement" => "top", :href => "https://twitter.com/SpanEngineering", :title => "Twitter", :target => "_blank"}
                  %i.fa.fa-twitter
              %li
                %a{"data-placement" => "top", :href => "https://in.linkedin.com/in/vishal-shivekar-97411812b", :title => "Linkedin", :target => "_blank"}
                  %i.fa.fa-linkedin
              %li
                %a{"data-placement" => "top", :href => "https://plus.google.com/u/0/101736486493236478496", :title => "Google plus", :target => "_blank"}
                  %i.fa.fa-google-plus
    %a.scrollup{:href => "#"}
      %i.fa.fa-angle-up.active
    /
      javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:src => "/assets/jquery.js"}
    %script{:src => "/assets/jquery.easing.1.3.js"}
    %script{:src => "/assets/bootstrap.min.js"}
    %script{:src => "/assets/jquery.fancybox.pack.js"}
    %script{:src => "/assets/jquery.fancybox-media.js"}
    %script{:src => "/assets/prettify.js"}
    %script{:src => "/assets/jquery.quicksand.js"}
    %script{:src => "/assets/setting.js"}
    %script{:src => "/assets/jquery.flexslider.js"}
    %script{:src => "/assets/animate.js"}
    %script{:src => "/assets/custom.js"}
    %script{:src => "js/custom.js"}
    %script{:src => "js/validate.js"}

app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Find me in app/views/contacts/show.html.erb</p>

app/views/features/index.html.haml
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %title Span Engineering
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "http://bootstraptaste.com", :name => "author"}/
    / css
    %link{:href => "/assets/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "/assets/jquery.fancybox.css", :rel => "stylesheet"}
    %link{:href => "/assets/flexslider.css", :rel => "stylesheet"}/
    %link{:href => "/assets/style.css", :rel => "stylesheet"}/
    / Theme skin
    %link{:href => "/assets/default.css", :rel => "stylesheet"}/
    / HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  %body
    #wrapper
      / start header
      %header
        .navbar.navbar-default.navbar-static-top
          .container
            .navbar-header
              %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              %a.navbar-brand{:href => ""}
                %span> Span Engineering
            .navbar-collapse.collapse
              %ul.nav.navbar-nav
                %li
                  = link_to "Home", root_path
                %li
                  = link_to "About Us", information_index_path
                %li
                  = link_to "Clients", clients_path
                %li
                  = link_to "Features", features_path
                %li
                  = link_to "Contact Us",contacts_path
      / end header
      %section.callaction
        .container
          .row
            .col-lg-12
              .big-cta
                .cta-text
                  %h2
                    %span Why
                    We are best?
      %section#content
        .container
          .row
            .col-lg-12
              .row
                .col-lg-3
                  .box
                    .box-gray.aligncenter
                      %h4 Quality Work
                      .icon
                        %i.fa.fa-desktop.fa-3x
                      %p
                        We define quality as conformance to our Customer's needs, both internal and external; and conformance to all quality requirements.
                .col-lg-3
                  .box
                    .box-gray.aligncenter
                      %h4 Low Cost
                      .icon
                        %i.fa.fa-pagelines.fa-3x
                      %p
                        We manufactured the products in low cost with maintaining it's standard quality as per client requirements as compare to other manufacturers.
                .col-lg-3
                  .box
                    .box-gray.aligncenter
                      %h4 Improvement
                      .icon
                        %i.fa.fa-edit.fa-3x
                      %p
                        Making continuous improvement is a part of every day and every job - through the use of team participation and measurements in a company.
                .col-lg-3
                  .box
                    .box-gray.aligncenter
                      %h4 Satisfaction
                      .icon
                        %i.fa.fa-smile-o.fa-3x
                      %p
                        Client satisafaction is our first priority. We got best feedback till date. We have also skilled work force to meet the highest quality of standards.
          .row
            .col-lg-12
              .row
                .col-lg-3
                  .box
                    .box-gray.aligncenter
                      %h4 ISO Certified
                      .icon
                        %i.fa.fa-certificate.fa-3x
                      %p
                        We are ISO 9001:2015 certified company by The Governing Board of The Progressive International Certifications Limited in September, 2016.
                .col-lg-3
                  .box
                    .box-gray.aligncenter
                      %h4 Masters of Risk
                      .icon
                        %i.fa.fa-tasks.fa-3x
                      %p
                        The most successful manufacturers will be both agile in confronting risks and resilient in adapting to disruptive change - in effect using it to their advantage.
                .col-lg-3
                  .box
                    .box-gray.aligncenter
                      %h4 Innovators of New
                      .icon
                        %i.fa.fa-lightbulb-o.fa-3x
                      %p
                        The development of new products and services for new markets, as well as existing customers, will be a recurring theme for best-in-class performers.
                .col-lg-3
                  .box
                    .box-gray.aligncenter
                      %h4 Global Orientation
                      .icon
                        %i.fa.fa-globe.fa-3x
                      %p
                        Successful manufacturers will be global, even if they never manufacture outside nation. They will open their all processes to benefit around the world.
      %footer
        .container
          .row
            .col-lg-5
              .widget
                %h5.widgetheading Get in touch with us
                %address
                  %strong Span Engineering
                  %br/
                  Gat No. 324, Chakan MIDC Phase II
                  %br/
                  Bhamboli, Tal - Khed, Dist - Pune
                %p
                  %i.icon-phone
                  8806315314 / 9130140895
                  %br/
                  %i.icon-envelope-alt
                  spanengineering25@gmail.com
            .col-lg-3
              .widget
                %h5.widgetheading Pages
                %ul.link-list
                  %li
                    = link_to "Home", root_path
                  %li
                    = link_to "About Us", information_index_path
                  %li
                    = link_to "Clients", clients_path
                  %li
                    = link_to "Features", features_path
                  %li
                    = link_to "Contact Us",contacts_path
            .col-lg-4
              .widget
                %h5.widgetheading © Span Engineering 2016
                %p
                  %address
                  %p
                    %strong Social Medial Links
                    %ul.social-network
                      %li
                        %a{"data-placement" => "top", :href => "https://www.facebook.com/Span-Engineering-Pvt-Ltd-Chakan-521609734702691/", :title => "Facebook", :target => "_blank"}
                          %i.fa.fa-facebook
                      %li
                        %a{"data-placement" => "top", :href => "https://twitter.com/SpanEngineering", :title => "Twitter", :target => "_blank"}
                          %i.fa.fa-twitter
                      %li
                        %a{"data-placement" => "top", :href => "https://in.linkedin.com/in/vishal-shivekar-97411812b", :title => "Linkedin", :target => "_blank"}
                          %i.fa.fa-linkedin
                      %li
                        %a{"data-placement" => "top", :href => "https://plus.google.com/u/0/101736486493236478496", :title => "Google plus", :target => "_blank"}
                          %i.fa.fa-google-plus
                %span Site Developed By
                %a{:href => "https://www.facebook.com/atul.nikhade", :target => "_blank"} Atul Nikhade
                .clear
    %a.scrollup{:href => "#"}
      %i.fa.fa-angle-up.active
    /
      javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:src => "/assets/jquery.js"}
    %script{:src => "/assets/jquery.easing.1.3.js"}
    %script{:src => "/assets/bootstrap.min.js"}
    %script{:src => "/assets/jquery.fancybox.pack.js"}
    %script{:src => "/assets/jquery.fancybox-media.js"}
    %script{:src => "/assets/prettify.js"}
    %script{:src => "/assets/jquery.quicksand.js"}
    %script{:src => "/assets/setting.js"}
    %script{:src => "/assets/jquery.flexslider.js"}
    %script{:src => "/assets/animate.js"}
    %script{:src => "/assets/custom.js"}

app/views/features/show.html.erb
<h1>Features#show</h1>
<p>Find me in app/views/features/show.html.erb</p>

app/views/information/show.html.erb
<h1>Information#show</h1>
<p>Find me in app/views/information/show.html.erb</p>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Span Engineering
    = favicon_link_tag 'logo.jpg'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |name, msg|
      .message
        %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"}
        = content_tag :div, msg,  :class => "alert alert-#{name}"
    = yield